### ISSUE TITLE
/usr/local/bin/ruby-cli-daemon: line 43: kill: (6490) - No such process

### ISSUE THREAD

**Issue by zedtux** [grosser/ruby-cli-daemon#1]
I'm trying this gem on macOS 10.14.5 :

```
$ ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
```

```
$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
CFPropertyList (2.2.8)
io-console (0.4.5)
json (1.8.3.1)
libxml-ruby (2.9.0)
nokogiri (1.5.6)
psych (2.1.0.1)
rdoc (4.2.1)
ruby-cli-daemon (0.2.0)
sqlite3 (1.3.11)
```

```
$ ruby-cli-daemon --version
0.2.0
```

```
$ ruby-cli-daemon rubocop --color -v
/usr/local/bin/ruby-cli-daemon: line 43: kill: (7324) - No such process
Failed to start worker, check /var/folders/fp/t3_g3n7d69q7sqrzy7j1h2_r0000gn/T/ruby_cli_daemon.log
```

**/var/folders/fp/t3_g3n7d69q7sqrzy7j1h2_r0000gn/T/ruby_cli_daemon.log** file :
```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Looks like bundler is a requirement for this gem so :

```
$ sudo gem install bundler
...
$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
bundler (2.0.1)
CFPropertyList (2.2.8)
io-console (0.4.5)
json (1.8.3.1)
libxml-ruby (2.9.0)
nokogiri (1.5.6)
psych (2.1.0.1)
rdoc (4.2.1)
ruby-cli-daemon (0.2.0)
sqlite3 (1.3.11)
```

```
$ ruby-cli-daemon rubocop --color -v
/usr/local/bin/ruby-cli-daemon: line 43: kill: (7450) - No such process
Failed to start worker, check /var/folders/fp/t3_g3n7d69q7sqrzy7j1h2_r0000gn/T/ruby_cli_daemon.log
```

**/var/folders/fp/t3_g3n7d69q7sqrzy7j1h2_r0000gn/T/ruby_cli_daemon.log** file :
```
cat /var/folders/fp/t3_g3n7d69q7sqrzy7j1h2_r0000gn/T/ruby_cli_daemon.log
/Library/Ruby/Gems/2.3.0/gems/ruby-cli-daemon-0.2.0/lib/ruby_cli_daemon.rb:45:in `preload_gem': undefined method `bin_file' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/ruby-cli-daemon-0.2.0/lib/ruby_cli_daemon.rb:17:in `start'
	from -e:1:in `<main>'
```

Looks like rubocop is not installed but this gem doesn't check that.

```
$ sudo gem install rubocop
...
$ gem list

*** LOCAL GEMS ***

ast (2.4.0)
bigdecimal (1.2.8)
bundler (2.0.1)
CFPropertyList (2.2.8)
io-console (0.4.5)
jaro_winkler (1.5.2)
json (1.8.3.1)
libxml-ruby (2.9.0)
nokogiri (1.5.6)
parallel (1.17.0)
parser (2.6.3.0)
psych (2.1.0.1)
rainbow (3.0.0)
rdoc (4.2.1)
rubocop (0.71.0)
ruby-cli-daemon (0.2.0)
ruby-progressbar (1.10.1)
sqlite3 (1.3.11)
unicode-display_width (1.6.0)
```

```
$ ruby-cli-daemon rubocop --color -v
/usr/local/bin/ruby-cli-daemon: line 43: kill: (7652) - No such process
Failed to start worker, check /var/folders/fp/t3_g3n7d69q7sqrzy7j1h2_r0000gn/T/ruby_cli_daemon.log
```

**/var/folders/fp/t3_g3n7d69q7sqrzy7j1h2_r0000gn/T/ruby_cli_daemon.log** file :
```
/Library/Ruby/Gems/2.3.0/gems/ruby-cli-daemon-0.2.0/lib/ruby_cli_daemon.rb:45:in `preload_gem': undefined method `bin_file' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/ruby-cli-daemon-0.2.0/lib/ruby_cli_daemon.rb:17:in `start'
	from -e:1:in `<main>'
```

Seems to be something else.

**Comment by zedtux** [comment]
Ah but creating folder, with a `Gemfile` with rubocop inside makes this gem working fine.

Is this supposed to be the way to use this gem or could it be used widely on the machine?
I'd like to use it with gems installed on the system (as you can see with the first ticket comment).

**Comment by grosser** [comment]
so you tried to use it in a folder "without a Gemfile" or "with a Gemfile without rubocop" ?

**Comment by grosser** [comment]
workaround would be to say "is this gem in bundler ? use it : use from system" ... that might not be too hard to add, I'll give it a try

**Comment by zedtux** [comment]
I tried in a folder without a `Gemfile`.

Actually what I'm trying to do is to use your gem to speedup the [chef](https://github.com/chef/chef) commands.

I have my chef-repo (a Git repo with all my chef files) where I'm running the chef commands (like knife for instance).

Without a `Gemfile`, I have what you see in the ticket. I have created the following `Gemfile` :

```ruby
# frozen_string_literal: true
source "https://rubygems.org"

gem 'chef'
gem 'knife-zero'
```

And now it's working.

**Comment by zedtux** [comment]
BTW the commands output is really strange :

```
$ chef exec knife ssh '*:*' 'ls -al /etc/tinc/k8sstg/hosts/' --local-mode ...
sa
xxxxxxxxxxxxxxx total 20
xxxxxxxxxxxxxxx drwxr-xr-x 2 root root 4096 May 30 21:31 .
xxxxxxxxxxxxxxx drwxr-xr-x 3 root root 4096 May 30 21:31 ..
xxxxxxxxxxxxxxx -rw-r--r-- 1 root root  854 May 30 20:19 bmi2660xx
xxxxxxxxxxxxxxx -rw-r--r-- 1 root root  854 May 30 20:36 bmi2681yy
xxxxxxxxxxxxxxx -rw-r--r-- 1 root root  854 May 30 20:36 bmi2681zz
xxxxxxxxxxxxxxx total 16
xxxxxxxxxxxxxxx drwxr-xr-x 2 root root 4096 May 30 20:23 .
xxxxxxxxxxxxxxx drwxr-xr-x 3 root root 4096 May 30 20:23 ..
xxxxxxxxxxxxxxx -rw-r--r-- 1 root root  854 May 30 20:23 bmi2660xx
xxxxxxxxxxxxxxx -rw-r--r-- 1 root root  854 May 30 20:23 bmi2681yy
xxxxxxxxxxxxxxx total 16
xxxxxxxxxxxxxxx drwxr-xr-x 2 root root 4096 May 30 20:23 .
xxxxxxxxxxxxxxx drwxr-xr-x 3 root root 4096 May 30 20:23 ..
xxxxxxxxxxxxxxx -rw-r--r-- 1 root root  854 May 30 20:23 bmi2660xx
xxxxxxxxxxxxxxx -rw-r--r-- 1 root root  854 May 30 20:23 bmi2681zz

$ chef exec ruby-cli-daemon knife ssh '*:*' 'ls -al /etc/tinc/k8sstg/hosts/' --local-mode ...
xxxxxxxxxxxxxxx bmi2660xx bmi2681yy bmi2681zz
xxxxxxxxxxxxxxx bmi2660xx bmi2681zz
xxxxxxxxxxxxxxx bmi2660xx bmi2681yy
```

**Comment by grosser** [comment]
that's a nice usecase ... chef is soo slow ... I'll play with that too

**Comment by zedtux** [comment]
It works fine excepted the commands output.

**Comment by grosser** [comment]
can you elaborate on what is wrong with the output, idk how chef output is supposed to look 🤷‍♂ 
or do you mean the xxxxx ?

**Comment by zedtux** [comment]
Well as you can see, the first command it the one without `ruby-cli-daemon`, while the second one is the same but ran with `ruby-cli-daemon`.

The 2 outputs should be the same, but they aren't.

The xxxxx are just some _hidden_ data.

**Comment by grosser** [comment]
knife now works

```
time ruby-cli-daemon knife -v
Chef: 13.12.3

real	0m0.143s
```

also non-bundler gems work
... if you have more issues, please open a new issue since this should either be fully or partially fixed :)

`gem i ruby_cli_daemon && ruby -rruby_cli_daemon -e "RubyCliDaemon.install '/usr/local/bin/ruby-cli-daemon'"` to update

**Comment by zedtux** [comment]
Hey thank you @grosser for the update, I'll give it a try !

**Comment by grosser** [comment]
I also added passing env vars now and some nice integration tests that should catch any regressions 🎉
